//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActID { get; set; }
        public System.DateTime ActDate { get; set; }
        public int EmpID { get; set; }
        public int TaskID { get; set; }
        public System.TimeSpan ActTime { get; set; }
        public string ActDescription { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Task Task { get; set; }
    }
}
